config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  namespace :admin do
    get 'homes/top'
    resources :products, only:[:new, :create, :index ,:show, :destroy, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :customer do
    resources :products, only:[:index, :show]
    resources :carts, only:[:index, :create, :update, :destroy]
    delete 'cart_all' => 'carts#destroy_all'
    resources :orders, only:[:new, :create, :update,:edit, :index]
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :contacts, only:[:new, :create, :index]
    get 'contacts/thanks' => 'contacts#thanks'
    resources :customers, only:[:edit,:update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :customer, optional: true
  belongs_to :product, optional: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = '個人情報を編集しました'
      redirect_to admin_customer_path(@customer)
    else
      flash[:danger] = '個人情報の編集に失敗しました'
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:name, :name_kana, :phone_namber, :email, :postcode, :prefecture_code, :address_city, :address_street)
  end
  
end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController

  def index
    @cart = Cart.where(customer_id: current_customer.id)
  end

  def create
      cart = Cart.new(cart_params)
       if Cart.where(product_id: params[:cart][:product_id] ,customer_id: current_customer.id).present?
       @cart = Cart.find_by(product_id: params[:cart][:product_id] ,customer_id: current_customer.id)
        new_quantity = @cart.quantity + cart.quantity
        @cart.update_attribute(:quantity, new_quantity)
       else
        cart.customer_id = current_customer.id
        cart.save
       end
       redirect_to customer_carts_path
  end

  def update
    cart = Cart.find(params[:id])
    cart.update(cart_params)
    redirect_to customer_carts_path
  end
  
  def destroy
    @products = Cart.find(params[:id])
    @products.destroy
    redirect_to customer_carts_path
  end

  def destroy_all
    @products = current_customer.carts
    @products.each do |f|
    f.destroy
    end
    redirect_to customer_carts_path
  end



  private
  def cart_params
    params.require(:cart).permit(:quantity, :customer_id, :product_id)
  end
end

app/controllers/customer/contacts_controller.rb
class Customer::ContactsController < ApplicationController

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to customer_contacts_thanks_path
    else
      redirect_to root_path
    end
  end

  def thanks
  end

  private

  def contact_params
    params.require(:contact).permit(:name,:contact)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to edit_customer_customer_path(current_customer.id), notice: "登録情報を編集しました"
    else
       render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :name_kana, :email, :phone_namber, :postcode, :prefecture_code, :address_city, :address_street)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def about
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @customer = current_customer
    @customer_form = CustomerForm.new(name: current_customer.name, email: current_customer.email, name_kana: current_customer.name_kana, postcode: current_customer.postcode,phone_namber: current_customer.phone_namber, prefecture_code: current_customer.prefecture_code, address_city: current_customer.address_city, address_street: current_customer.address_street)
    @cart = current_customer.carts
  end

  def create
    # order = Order.new(order_params)
    # order.customer_id = current_customer.id
    order = current_customer.orders.new(order_params)
    current_customer.carts.each do |f|
      order.product_id = f.product_id;
      order.quantity = f.quantity;
      order.price = f.product.price;
      f.destroy
    end
    order.save
    redirect_to customer_orders_thanks_path
  end

  def update
    @customer = current_customer
    # @customer = Customer.find(params[:customer_id])

    if @customer.update(customer_params)
      if params[:select_address] == "new_deliverey_address"
        redirect_to customer_orders_confirm_path(new_deliverey_address: true,customer_new_params: customer_new_params)
      else
        redirect_to customer_orders_confirm_path(new_deliverey_address: false)
      end
    else
      redirect_to new_customer_order_path
    end
  end

  def confirm
    @customer = current_customer
    @cart = current_customer.carts
    @order = Order.new(params[:order])
    if params['new_deliverey_address'] == "false"
      @order.postcode = current_customer.postcode
      @order.email = current_customer.email
      @order.name = current_customer.name
      @order.name_kana = current_customer.name_kana
      @order.phone_namber = current_customer.phone_namber
      @order.prefecture_code = current_customer.prefecture_code
      @order.address_city = current_customer.address_city
      @order.address_street = current_customer.address_street
    else
      params[:new_deliverey_address]
      @new_address = params[:new_deliverey_address]
      @email_new = params[:customer_new_params][:email_new]
      @phone_namber_new = params[:customer_new_params][:phone_namber_new]
      @name_kana_new = params[:customer_new_params][:name_kana_new]
      @name_new = params[:customer_new_params][:name_new]
      @postcode_new = params[:customer_new_params][:postcode_new]
      @prefecture_code_new = params[:customer_new_params][:prefecture_code_new]
      @address_city_new = params[:customer_new_params][:address_city_new]
      @address_street_new = params[:customer_new_params][:address_street_new]
      @order.postcode = @postcode_new
      @order.email = @email_new
      @order.name = @name_new
      @order.name_kana = @name_kana_new
      @order.phone_namber = @phone_namber_new
      @order.prefecture_code = @prefecture_code_new
      @order.address_city = @address_city_new
      @order.address_street = @address_street_new
    end
  end

  def thanks
  end

  def index
    @orders = Order.all.includes(:product)
  end

  def show
    @order = Order.find(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postcode, :name_kana, :name ,:phone_namber, :prefecture_code, :address_city, :address_street, :email)
  end

  def customer_params
    params.require(:customer_form).permit( :postcode, :name_kana, :name ,:phone_namber, :prefecture_code, :address_city, :address_street, :email)
  end

  def customer_new_params
    params.require(:customer_form).permit( :postcode_new, :name_kana_new, :name_new ,:phone_namber_new, :prefecture_code_new, :address_city_new, :address_street_new, :email_new)
  end


end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :introduction, :price )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/contacts_helper.rb
module Customer::ContactsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/customer/orders/confirm.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>注文内容の確認</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3 text-center">
    <table class="table table-bordered">
          <tr>
            <th>商品名</th>
            <th>数量</th>
            <th>小計（税込）</th>
          </tr>
          <% i = 0 %>
          <% @cart.each do |cart| %>
            <tr>
              <td><%= attachment_image_tag cart.product, :image, size: "50x50" %><%= cart.product.name %></td>
              <td><%= cart.quantity %></td>
              <td><% subtotal = cart.quantity * cart.product.price %><%= subtotal.to_i %>円</td>
            </tr>
            <% i = i + cart.quantity * cart.product.price  %>
          <% end %>
          </table>
          <p class="text-right">
            送料・・・・・・・・・・・・800円</br>
            配送方法・・・・・弊社指定配送方法</br>
            商品合計（税込）・・・・・<%= i.to_i %>円
          </p>
          <hr>
          <table class="table table-bordered">
            <td>お支払い合計　：<%= i + 800 %>円</td>
          </table>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <table class="table table-bordered">
      <td>
        ・返品期限</br>
        商品の返品・交換には初期不良の場合以外では応じられません。</br></br>
        ・返品送料</br>
        初期不良、発送商品間違いの場合、当店着払いにて対応いたします。
      </td>
    </table>
  </div>
</div>

<div class="container">
  <div class="p-3 my-1">
    <strong>注文内容確認</strong><br>
    <table class="table table-bordered">
      <tr>
        <td>注文者情報</td>
      </tr>
      <tr>
        <td>お名前</td>
        <td><%= current_customer.name %></td>
      </tr>
      <tr>
        <td>お名前フリガナ</td>
        <td><%= current_customer.name_kana %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= current_customer.phone_namber %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= current_customer.email %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td>(<%= current_customer.postcode %>)<%= current_customer.prefecture_code %><%= current_customer.address_city %><%= current_customer.address_street %></td>
      </tr>
    </table>


    <table class="table table-bordered">
      <tr>
        <td>商品お届け先</td>
      </tr>
      <tr>
        <td>お名前</td>
        <td><%= @order.name %></td>
      </tr>
      <tr>
        <td>お名前フリガナ</td>
        <td><%= @order.name_kana %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @order.phone_namber %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @order.email %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td>（<%= @order.postcode %>）<%= @order.prefecture_code %><%= @order.address_city %><%= @order.address_street %></td>
      </tr>
    </table>

    <table class="table table-bordered">
      <tr>
        <td>支払い方法</td>
        <td>
          <% if @order.payment_method == true %>
            <p>クレジットカード</p>
          <% else %>
            <p>銀行振り込み</p>
          <% end %>
        </td>
      </tr>
    </table>

    <%= form_with :model => @order, url:customer_orders_path, method: :post, local: true  do |f| %>
    <%#= form_with scope: 'new_order', url:customer_orders_path, method: :post, local: true  do |f| %>
      <%= f.hidden_field :name, :value => @order.name %>
      <%= f.hidden_field :name_kana, :value => @order.name_kana %>
      <%= f.hidden_field :phone_namber, :value => @order.phone_namber %>
      <%= f.hidden_field :email, :value => @order.email %>
      <%= f.hidden_field :postcode, :value => @order.postcode %>
      <%= f.hidden_field :prefecture_code, :value => @order.prefecture_code %>
      <%= f.hidden_field :address_city, :value => @order.address_city %>
      <%= f.hidden_field :address_street, :value => @order.address_street %>
    <%= f.submit "注文を確定する", class: "btn btn-success col-xs-2 col-xs-offset-5" %>
    <% end %>

  </div>
</div>

app/views/customer/orders/index.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>注文一覧</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3 text-center">
    <% @orders.each do |order| %>
    <table class="table table-bordered">
      <thead>
        <tr class="table-primary">
          <th>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払い金額</th>
          <th>注文詳細</th>
        </tr>
      </thead>
      <tbody>
        <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          〒<%= order.postcode %></br>
          <%= order.prefecture_code %><%= order.address_city %><%= order.address_street %></br>
          <%= order.name %>
        </td>
        <td><%= order.product.name %></td>
        <td><%= order.price %>円（税込）</td>
        <td><%= link_to "詳細", customer_order_path(order), class: "btn btn-success" %></td>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
    <div class="p-3 my-3">
      <h5>カートには以下の商品が入っています</h5>
        <table class="table table-bordered">
          <tr class="table-primary">
            <th>商品情報</th>
            <th>数量</th>
            <th>小計（税込）</th>
          </tr>
        <% i = 0 %>
        <% @cart.each do |cart| %>
          <tr>
            <td><%= attachment_image_tag cart.product, :image, size: "50x50" %><%= cart.product.name %></td>
            <td><%= cart.quantity %></td>
            <td><% subtotal = cart.quantity * cart.product.price %><%= subtotal.to_i %>円</td>
          </tr>
          <% i = i + cart.quantity * cart.product.price  %>
        <% end %>
        </table>
        <div class="text-right">商品合計（税込）：　　<%= i.to_i %>円</div>
    </div>
</div>


<div class="container">
  <div class="p-3 my-1">
    <%= form_with(model: [@customer_form], url:  customer_order_path(@customer),local:true,method: :patch) do |f| %>
        <table class="table table-bordered">
          <tr class="table-primary">
            <th>注文者情報入力</th>
          </tr>
          <tr>
            <td class="table-secondary">お名前　※必須</td>
            <td><%= f.text_field :name %>　（例）山田太郎</td>
          </tr>
          <tr>
            <td class="table-secondary">お名前フリガナ ※必須</td>
            <td><%= f.text_field :name_kana %>　（例）ヤマダタロウ</td>
          </tr>
          <tr>
            <td class="table-secondary">電話番号（ハイフンなし）</td>
            <td><%= f.text_field :phone_namber %></td>
          </tr>
          <tr>
            <td class="table-secondary">メールアドレス</td>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <td class="table-secondary">郵便番号</td>
            <td><%= f.text_field :postcode, autofocus: true, autocomplete: "postcode", id:"customer_postcode" %></td>
          </tr>
          <tr>
            <td class="table-secondary">住所</td>
            <td>
              都道府県</br>
              <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, id:"customer_prefecture_code" %></br>
              市区町村</br>
              <%= f.text_field :address_city, autofocus: true, autocomplete: "address_city", id:"customer_address_city" %></br>
              それ以降の住所</br>
              <%= f.text_field :address_street, autofocus: true, autocomplete: "address_street", id:"customer_address_street" %></br>
              ※マンション・アパート名は必ず入力してください。</br>
              ※入力されている住所が勤務先の場合は「会社名・部署名」なども入力してください。
            </td>
          </tr>

        </table>

         <form autocomplete=off>

          <hr>
          <label>
            <input class="js-check" type="radio" name="select_address" value="customer_address" onclick="formSwitch(1)"checked >注文者の住所にお届けする
          </label></br>

          <label>
            <input class="js-check" type="radio" name="select_address" value="new_deliverey_address" onclick="formSwitch(2)">新しいお届け先を入力する
          </label>
          <span id="sample">
          <table class="table table-bordered">
            <tr>
              <td class="table-secondary">お名前　※必須</td>
              <td><%= f.text_field :name_new %>　（例）山田太郎</td>
            </tr>
            <tr>
              <td class="table-secondary">お名前フリガナ ※必須</td>
              <td><%= f.text_field :name_kana_new %>　（例）ヤマダタロウ</td>
            </tr>
            <tr>
              <td class="table-secondary">電話番号（ハイフンなし）</td>
              <td><%= f.text_field :phone_namber_new %></td>
            </tr>
            <tr>
              <td class="table-secondary">メールアドレス</td>
              <td><%= f.email_field :email_new %></td>
            </tr>
            <tr>
              <td class="table-secondary">郵便番号</td>
              <td><%= f.text_field :postcode_new, autofocus: true, autocomplete: "postcode", id:"customer_postcode" %></td>
            </tr>
            <tr>
              <td class="table-secondary">住所</td>
              <td>
                都道府県</br>
                <%= f.collection_select :prefecture_code_new, JpPrefecture::Prefecture.all, :code, :name, id:"customer_prefecture_code" %></br>
                市区町村</br>
                <%= f.text_field :address_city_new, autofocus: true, autocomplete: "address_city", id:"customer_address_city" %></br>
                それ以降の住所</br>
                <%= f.text_field :address_street_new, autofocus: true, autocomplete: "address_street", id:"customer_address_street" %></br>
                ※マンション・アパート名は必ず入力してください。</br>
                ※入力されている住所が勤務先の場合は「会社名・部署名」なども入力してください。
              </td>
            </tr>
          </table>
            </span>

            <script>
              var selecterBox = document.getElementById('sample');
                function formSwitch() {
                  check = document.getElementsByClassName('js-check')
                  console.log(check[0])
                  if (check[0].checked) {
                      selecterBox.style.display = "none";

                  } else if (check[1].checked) {
                      selecterBox.style.display = "block";

                  } else {
                      selecterBox.style.display = "none";
                  }
                }
                window.addEventListener('load', formSwitch());

                function entryChange2(){
                    if(document.getElementById('changeSelect')){
                    id = document.getElementById('changeSelect').value;
                }
                }

                $(function() {
                  return $('#customer_postcode').jpostal({
                    postcode: ['#customer_postcode'],
                    address: {
                      '#customer_prefecture_code': '%3',
                      '#customer_address_city': '%4',
                      '#customer_address_street': '%5%6%7',
                    },
                  });
                });
            </script>
            <hr>

            <table class="table table-bordered">
              <tr class="table-primary">
                <th>支払い方法の選択</th></br>
              </tr>
              <tr>
                <td>
                    <%= f.radio_button :payment_method, 0, checked: true %> クレジットカード<br>
                    <%= f.radio_button :payment_method, 1 %> 銀行振込
                </td>
              </tr>
            </table>


            <table class="table table-bordered">
              <tr class="table-primary">
                <th>配送方法</th>
              </tr>
              <tr>
                <td class="table-secondary"><%= f.radio_button :delivery_method, 0, checked: true %> 弊社指定配送方法<br>
                <td>
                  ◆佐川急便でのお届け</br>
                  【お届けの目安】</br>
                  関東・近畿・中国・四国は出荷日の翌日若しくは翌々日。</br>
                  東北・九州は出荷日から2～3日程度。</br>
                  北海道及び沖縄・離島に関しては、出荷日より3～5日程度。</br>
                  【配送料金】</br>
                  <li>全国一律800円</li>
                  <li>〇〇急便でのお届</li></br>
                </td>
              </tr>
            </table>

            <div class="confirm">
					    <%= f.submit "確認画面へ進む", class:"btn btn-success" %>
					  </div>
        <% end %>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>注文履歴詳細</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <p>注文内容</p>
    <table class="table table-bordered">
      <tr>
        <td class="table-primary">注文日</td>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td class="table-primary">配送先</td>
        <td>
          〒<%= @order.postcode %></br>
          <%= @order.prefecture_code %><%= @order.address_city %><%= @order.address_street %></br>
          <%= @order.name %>
        </td>
      </tr>
      <tr>
        <td class="table-primary">支払い方法</td>
        <td>銀行振り込み</td>
      </tr>
    </table>

    <% i = 0 %>
    <% subtotal = 0 %>
    <p>注文情報</p>
    <table class="table table-bordered">
      <tr>
        <td class="table-primary">商品</td>
        <td class="table-primary">単価（税込）</td>
        <td class="table-primary">個数</td>
        <td class="table-primary">小計</td>
      </tr>
      <tr>
        <td><%= @order.product.name %></td>
        <td><%= @order.product.price %>円</td>
        <td><%= @order.quantity %></td>
        <td><% subtotal = @order.quantity * @order.product.price %><%= subtotal.to_i %>円</td>
      </tr>
    </table>

    <p>請求情報</p>
    <table class="table table-bordered">
      <tr>
        <td class="table-primary">商品合計</td>
        <td><%= subtotal.to_i %>円</td>
      </tr>
      <tr>
        <td class="table-primary">送料</td>
        <td>800円</td>
      </tr>
      <tr>
        <td class="table-primary">合計金額</td>
        <td><%= subtotal.to_i + 800 %>円（税込）</td>
      </tr>
    </table>
  </div>
</div>

app/views/customer/orders/thanks.html.erb
<body class="text-center">
  </br>
  </br>
  </br>
  </br>
  </br>
  </br>
  </br>
  </br>
  <h1>ご注文ありがとうございました。</h1>
</body>