config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  namespace :admin do
    get 'homes/top'
    resources :products, only:[:new, :create, :index ,:show, :destroy, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :customer do
    resources :products, only:[:index, :show]
    resources :carts, only:[:index, :create, :update, :destroy]
    delete 'cart_all' => 'carts#destroy_all'
    resources :orders, only:[:new, :create, :update,:edit, :index]
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :contacts, only:[:new, :create, :index]
    get 'contacts/thanks' => 'contacts#thanks'
    resources :customers, only:[:edit,:update]
  end

end

app/models/product.rb
class Product < ApplicationRecord
  
  attachment :image
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update!(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :introduction, :price )
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>商品編集</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <table class="table table-bordered">
    <%= form_with model: [:admin, @product], local:true do |f| %>
      <tr>
        <td>商品画像</td>
        <td>
          <%= attachment_image_tag @product, :image, :size =>'100x100' %>
          <%= f.attachment_field :image %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :name, "商品名" %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :introduction, "商品説明" %></td>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <td><%= f.label :price, "価格（税込）" %></td>
        <td><%= f.text_field :price %>円</td>
      </tr>
    </table>
    <%= f.submit "編集", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
      <h1>商品一覧</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <%= link_to "NEW ITEMS", new_admin_product_path, class:"btn btn-info" %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>価格</th>
            </tr>
          </thead>

          <% @products.each do |product| %>
          <tbody>
            <tr>
              <td><%= product.id %></td>
              <td><%= link_to product.name, admin_product_path(product.id) %></td>
              <td><%= product.price %>円</td>
            </tr>
          </tbody>
          <% end %>
        </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>商品新規登録</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <%= form_with model: [:admin, @product], local:true do |f| %>
    <table class="table table-bordered">
      <tr>
        <td>商品画像</td>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <td><%= f.label :name, "商品名" %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :introduction, "商品説明" %></td>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <td><%= f.label :price, "価格（税込）" %></td>
        <td><%= f.text_field :price %>円</td>
      </tr>
    </table>
    <%= f.submit "新規登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md4 max-auto text-center">
    <h1>商品詳細</h1>
  </div>
</div>

<div class="container">
  <div class="p-3 my-3">
    <table class="table table-bordered">
      <tr>
        <td>商品画像</td>
        <td><%= attachment_image_tag @product, :image, :size =>'300x300' %></td>
      </tr>
      <tr>
        <td>商品名</td>
        <td><%= @product.name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= @product.introduction %></td>
      </tr>
      <tr>
        <td>価格</td>
        <td><%= @product.price.to_s %>円</td>
      </tr>
    </table>
    <%= link_to "編集", edit_admin_product_path(@product.id), class: "btn btn-success" %>
    <%= link_to "削除", admin_product_path(@product.id), method: :delete,  class: "btn btn-danger" %>
  </div>
</div>