config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  namespace :admin do
    get 'homes/top'
    resources :products, only:[:new, :create, :index ,:show, :destroy, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :customer do
    resources :products, only:[:index, :show]
    resources :carts, only:[:index, :create, :update, :destroy]
    delete 'cart_all' => 'carts#destroy_all'
    resources :orders, only:[:new, :create, :update,:edit, :index]
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :contacts, only:[:new, :create, :index]
    get 'contacts/thanks' => 'contacts#thanks'
    resources :customers, only:[:edit,:update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :customer
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :customer, optional: true
  belongs_to :product, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  
  attachment :image
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update!(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters , if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :postcode, :prefecture_code, :address_city, :address_street, :phone_namber])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/contacts_helper.rb
module Customer::ContactsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helploss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/280f947faa.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light mb-2" style="background-color:#e6e6fa">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Help Loss', customer_products_path, class: 'nav-link text-dark' %>
        <i class="fas fa-hands-helping fa-2x"></i>
        <%# if customer_signed_in? %>
        <!--<div>ようこそ<%#= current_customer.name %>様</div>-->
        <%# end %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li><%= link_to '買う　', customer_products_path, class:"fas fa-store fa-lg" %></li>
              <li><%= link_to 'カート　', customer_carts_path, class:"fas fa-shopping-cart fa-lg" %></li>
              <li><%= link_to '売る　', customer_contacts_path, class:"fas fa-users fa-lg" %></li>
              <li><%= link_to 'マイページ　', edit_customer_customer_path(current_customer.id), class: "fas fa-users-cog fa-lg" %></li>
              <li><%= link_to "About　", root_path, class: "fas fa-tv fa-lg" %></li>
              <li><%= link_to "ログアウト　", destroy_customer_session_path, class:"fas fa-sign-out-alt fa-lg", method: :delete %></li>
            <% elsif admin_signed_in? %>
              <li><%= link_to '商品一覧　', admin_products_path, class:"btn btn-default" %></li>
              <li><%= link_to '会員一覧　', admin_customers_path, class:"btn btn-default" %></li>
              <li><%= link_to 'ログアウト　', destroy_admin_session_path, class:"btn btn-default", method: :delete %></li>
            <% else %>
              <li><%= link_to "新規登録　", new_customer_registration_path, class:"fas fa-user-plus fa-lg" %></li>
              <li><%= link_to "ログイン　", new_customer_session_path, class:"fas fa-sign-in-alt fa-lg" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>

<!--<footer class="footer">-->
<!--  <div class="container">-->
<!--    <p class="text-center">© 2021 Help Loss JAPAN inc.</p>-->
<!--  </div>-->
<!--</footer>-->

</html>